### Dataframe 
Collection of multiple series is called Dataframe or df.

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [3]:
# Creating a DataFrame

df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]

df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting and indexing of columns

In [7]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [9]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [11]:
df[['Name', 'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [14]:
df2["Designation"] = ["Doctor", "Eng.", "Doctor", "Eng."]

In [15]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

### Remove a column

In [ ]:
# If we don't provide inplace=True (then it won't be deleted truly)
# If we don't provide axis = 1, then it won't be searching in the columns for that column_name we provide
# By default it'll search in the rows with axis=0 then it'll give error because er provided it column_name
df.drop("Salary", axis=1, inplace=True)

In [21]:
df

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

In [22]:
# Removing 2 cols at once

df.drop(["Age", "City"], axis=1, inplace=True)

In [23]:
df

    Name Designation
0   John      Doctor
1   Anna        Eng.
2  Peter      Doctor
3  Linda        Eng.

In [24]:
# Removing row
df.drop(1, axis=0, inplace=True)

In [25]:
df

    Name Designation
0   John      Doctor
2  Peter      Doctor
3  Linda        Eng.

### Selecting a row

In [28]:
df2.loc[[0, 1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000        Eng.

In [30]:
df2.loc[[3]]

    Name  Age    City  Salary Designation
3  Linda   42  London   85000        Eng.

In [31]:
# loc - Location
# iloc - Index Location
df2.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation      Eng.
Name: 3, dtype: object

### Selecting subset of rows and columns

In [33]:
df2.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

### Conditional Selection

In [34]:
# People whose age is above 30

df2[df2['Age'] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000        Eng.

In [36]:
# People whose age is above 30 and City must be Paris

df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.